### ISSUE TITLE
打包好的插件也发出来呗

### ISSUE THREAD

**Issue by sandianyiyuan** [iuuniang/IIME#2]
打包好的插件也发出来呗

**Comment by sandianyiyuan** [comment]
我以为要`.plgx`的才能用，看文档才知道原来`.dll`格式的也可以。
赞一个

**Comment by iuuniang** [comment]
> 我以为要`.plgx`的才能用，看文档才知道原来`.dll`格式的也可以。 赞一个

可以通过KeePass的官方文档[Plugin Development (2.x)](https://keepass.info/help/v2_dev/plg_index.html)，用KeePass.exe命令行生成plgx插件。
